In [1]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in .\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:

data = pd.read_csv("../laptop_price.csv", encoding='latin1')

In [4]:
data.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00

# Dataset Loaded

In [5]:
data.shape

(1303, 12)

In [6]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   str
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 122.3 KB

In [8]:
# Strip the 'GB' text before converting
data['Ram'] = data['Ram'].astype(str).str.replace('GB', '', regex=False).astype('int32')

# For Weight, strip 'kg' before converting
data['Weight'] = data['Weight'].astype(str).str.replace('kg', '', regex=False).astype('float32')

In [9]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   int32
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   float32
 11  Price_euros       1303 non-null   float64
dtypes: float32(1), float64(2), int32(1), int64(1), str(7)
memory usage: 112.1 KB

In [11]:
data.corr(numeric_only=True)['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [12]:
def add_company(inpt):
    if inpt == 'Samsung' or inpt == 'Razer'or inpt == 'Mediacom'or inpt== 'Microsoft'or inpt=='Xiaomi'or inpt=='Vero'or inpt=='Chuwi'or inpt=='Google ' or inpt=='Fujitsu'or inpt=='LG'or inpt=='Huawei':
        return 'Other'
    else:    
        return inpt

data['Company'] =  data['Company'].apply(add_company)

In [13]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       48
Toshiba     48
Apple       21
Google       3
Name: count, dtype: int64

In [14]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['Ips']= data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [15]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [16]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [17]:
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz              190
Intel Core i7 7700HQ 2.8GHz             146
Intel Core i7 7500U 2.7GHz              134
Intel Core i7 8550U 1.8GHz               73
Intel Core i5 8250U 1.6GHz               72
                                       ...
Intel Core i5 7200U 2.7GHz                1
Intel Pentium Dual Core 4405Y 1.5GHz      1
Intel Core M 6Y54 1.1GHz                  1
Samsung Cortex A72&A53 2.0GHz             1
AMD E-Series 9000 2.2GHz                  1
Name: count, Length: 118, dtype: int64

In [18]:
data['Cpu_name']= data['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))

In [19]:
data['Cpu_name'].value_counts()

Cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
Intel Atom x5-Z8550           4
AMD A8-Series 7410            4
AMD Ryzen 1700                3
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD E-Series E2-9000e         2
Intel Xeon E3-1505M           2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD A10-Series 9600P          2
AMD A10-Series 9620P          2
AMD E-Series 7110             2
AMD A9-Series A9-9420         2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD Ryzen 1600                1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [20]:
def set_processor(name):
    if name == 'Intel Core i7' or name == 'Intel Core i5' or name == 'Intel core i3':
        return name
    else:
        if name.split()[0] == 'AMD':
            return 'AMD'
        else:
            return 'Other'
            
data['Cpu_name'] = data['Cpu_name'].apply(set_processor)

In [21]:
data['Cpu_name'].value_counts()

Cpu_name
Intel Core i7    527
Intel Core i5    423
Other            291
AMD               62
Name: count, dtype: int64

In [22]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [23]:
data['Gpu_name']= data['Gpu'].apply(lambda x:" ".join(x.split()[0:1]))

In [24]:
data['Gpu_name'].value_counts()

Gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [25]:
data.shape

(1303, 16)

In [26]:
data = data[data['Gpu_name'] != 'ARM']

In [27]:
data.shape

(1302, 16)

In [28]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,Cpu_name,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5,Intel

In [29]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [30]:
def set_os(inpt):
    if inpt == 'Windows 10' or inpt == 'Windows 7' or inpt == 'Windows 10 S':
        return 'Windows'
    elif inpt == 'macOS' or inpt =='Mac OS X':
        return 'Mac'
    elif inpt == 'Linux':
        return inpt
    else:
        return 'Other'

            
data['OpSys'] = data['OpSys'].apply(set_os)

In [31]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,Cpu_name,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,Mac,1.83,2537.45,0,1,Intel Core i7,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,Mac,1.37,1803.60,0,1,Intel Core i5,Intel

In [32]:
data= data.drop(columns=['laptop_ID', 'Inches', 'Product', 'Cpu', 'Gpu'])

In [33]:
data.head(2)

,Company,TypeName,ScreenResolution,Ram,OpSys,Weight,Price_euros,Touchscreen,Ips,Cpu_name,Gpu_name
0,Apple,Ultrabook,IPS Panel Retina Display 2560x1600,8,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,1440x900,8,Mac,1.34,898.94,0,0,Intel Core i5,Intel

In [34]:
data = pd.get_dummies(data)

In [35]:
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_Google,...,OpSys_Mac,OpSys_Other,OpSys_Windows,Cpu_name_AMD,Cpu_name_Intel Core i5,Cpu_name_Intel Core i7,Cpu_name_Other,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia
0,8,1.37,1339.69,0,1,False,True,False,False,False,...,True,False,False,False,True,False,False,False,True,False
1,8,1.34,898.94,0,0,False,True,False,False,False,...,True,False,False,False,True,False,False,False,True,False

In [36]:
print(data.dtypes)

Ram                         int32
Weight                    float32
Price_euros               float64
Touchscreen                 int64
Ips                         int64
                           ...
Cpu_name_Intel Core i7       bool
Cpu_name_Other               bool
Gpu_name_AMD                 bool
Gpu_name_Intel               bool
Gpu_name_Nvidia              bool
Length: 71, dtype: object

In [37]:
# After creating dummies
data = pd.get_dummies(data, drop_first=True)

# Convert all bool columns to int
data = data.astype(int)

In [39]:
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_Google,...,OpSys_Mac,OpSys_Other,OpSys_Windows,Cpu_name_AMD,Cpu_name_Intel Core i5,Cpu_name_Intel Core i7,Cpu_name_Other,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia
0,8,1,1339,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1,8,1,898,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [40]:
X = data.drop('Price_euros', axis=1)
y = data['Price_euros']

In [43]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in .\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in .\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\Lib\site-packages (from scikit-learn) (3.6.0)

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [45]:
X_train.shape, X_test.shape

((976, 70), (326, 70))

In [46]:
def model_acc(model):
    model.fit(X_train,y_train)
    acc = model.score(X_test,y_test)
    print(str(model)+ ' --> '+str(acc))

# LinearRegression Accurace Test

In [47]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

LinearRegression() --> 0.7257806419381723

# LassoRegression Accuracy Test

In [48]:
from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

Lasso() --> 0.731103922907731

# DecesionTressRegression Accuracy Test

In [50]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

DecisionTreeRegressor() --> 0.5679463219238269

# RandomForest Accuracy Test

In [51]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

RandomForestRegressor() --> 0.7721744819349958

In [54]:
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10,50,100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)
grid_fit = grid_obj.fit(X_train, y_train)
best_model = grid_fit.best_estimator_
best_model

RandomForestRegressor(criterion='absolute_error', n_estimators=50)

In [55]:
best_model.score(X_test, y_test)

0.7854253949166082

In [58]:
import pickle
with open('predictor.pickle','wb') as file:
    pickle.dump(best_model, file)

In [60]:
X_train.columns

Index(['Ram', 'Weight', 'Touchscreen', 'Ips', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_Google', 'Company_HP',
       'Company_Lenovo', 'Company_MSI', 'Company_Other', 'Company_Toshiba',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'ScreenResolution_1366x768', 'ScreenResolution_1440x900',
       'ScreenResolution_1600x900', 'ScreenResolution_1920x1080',
       'ScreenResolution_2560x1440',
       'ScreenResolution_4K Ultra HD / Touchscreen 3840x2160',
       'ScreenResolution_4K Ultra HD 3840x2160',
       'ScreenResolution_Full HD / Touchscreen 1920x1080',
       'ScreenResolution_Full HD 1920x1080',
       'ScreenResolution_IPS Panel 1366x768',
       'ScreenResolution_IPS Panel 2560x1440',
       'ScreenResolution_IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'ScreenResolution_IPS Panel 4K Ultra HD 3840x2160',
       'ScreenResolution_IPS Panel Full HD / Touchscreen 1920x1080',
       'ScreenResolution_IPS Panel Full HD 1366x768',
       'ScreenResolution_IPS Panel Full HD 1920x1080',
       'ScreenResolution_IPS Panel Full HD 1920x1200',
       'ScreenResolution_IPS Panel Full HD 2160x1440',
       'ScreenResolution_IPS Panel Full HD 2560x1440',
       'ScreenResolution_IPS Panel Quad HD+ / Touchscreen 3200x1800',
       'ScreenResolution_IPS Panel Quad HD+ 2560x1440',
       'ScreenResolution_IPS Panel Quad HD+ 3200x1800',
       'ScreenResolution_IPS Panel Retina Display 2304x1440',
       'ScreenResolution_IPS Panel Retina Display 2560x1600',
       'ScreenResolution_IPS Panel Retina Display 2736x1824',
       'ScreenResolution_IPS Panel Retina Display 2880x1800',
       'ScreenResolution_IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
       'ScreenResolution_IPS Panel Touchscreen 1366x768',
       'ScreenResolution_IPS Panel Touchscreen 1920x1200',
       'ScreenResolution_IPS Panel Touchscreen 2560x1440',
       'ScreenResolution_Quad HD+ / Touchscreen 3200x1800',
       'ScreenResolution_Quad HD+ 3200x1800',
       'ScreenResolution_Touchscreen / 4K Ultra HD 3840x2160',
       'ScreenResolution_Touchscreen / Full HD 1920x1080',
       'ScreenResolution_Touchscreen / Quad HD+ 3200x1800',
       'ScreenResolution_Touchscreen 1366x768',
       'ScreenResolution_Touchscreen 2256x1504',
       'ScreenResolution_Touchscreen 2400x1600',
       'ScreenResolution_Touchscreen 2560x1440', 'OpSys_Linux', 'OpSys_Mac',
       'OpSys_Other', 'OpSys_Windows', 'Cpu_name_AMD',
       'Cpu_name_Intel Core i5', 'Cpu_name_Intel Core i7', 'Cpu_name_Other',
       'Gpu_name_AMD', 'Gpu_name_Intel', 'Gpu_name_Nvidia'],
      dtype='str')

In [ ]:
X_train.shape

In [ ]:
X_train.columns

# GetPrediction Example

In [64]:
import pandas as pd
import numpy as np

# Get the exact column order from training
columns = X_train.columns   # this is your 70-feature list

# Start with zeros for all features
input_dict = {col: 0 for col in columns}

# Now set the values you want to test
# Example: mapping your 31 values into the right features
input_dict["Ram"] = 8
input_dict["Weight"] = 1
input_dict["Touchscreen"] = 3
input_dict["Ips"] = 1

# Example categorical one-hot flags:
input_dict["Company_Dell"] = 1
input_dict["TypeName_Notebook"] = 1
input_dict["ScreenResolution_1920x1080"] = 1
input_dict["OpSys_Windows"] = 1
input_dict["Cpu_name_Intel Core i5"] = 1
input_dict["Gpu_name_Nvidia"] = 1

# Convert to DataFrame with the same column order
new_data = pd.DataFrame([input_dict], columns=columns)

# Predict
prediction = best_model.predict(new_data)
print("Predicted price:", prediction[0])

Predicted price: 991.72